config/routes.rb
Rails.application.routes.draw do
  get 'restaurants/search' => 'restaurants#search'
  devise_for :users
  root to: 'pages#home'
    resources :restaurants do
      resources :bookings
      resources :reviews
    end
  get    "bookings/:id/accept",      to: "bookings#accept", as: "accept_booking"
  get    "bookings/:id/reject",      to: "bookings#reject", as: "reject_booking"
  resources :users, only: [:show, :edit, :update]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :restaurant
  belongs_to :user
  validates :booking_date, presence: true
  validates :status, presence: true, acceptance:  { accept: ["accepted", "declined", "pending"] }

  def validate
    self.status = "validée"
  end

end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  belongs_to :users
  has_many :bookings
  geocoded_by :address
  after_validation :geocode, if: :address_changed?
  validates :name, presence: true
  # validates :chef, presence: true
  validates :address, presence: true
  validates :description, presence: true
  RATINGS = [0, 1, 2, 3, 4, 5]
  validates :average_rating, inclusion: { in: RATINGS }, :allow_nil => true
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :restaurant
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :bookings
  has_many :reviews
  has_many :restaurants
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  def index
    @bookings = Booking.all
  end

  def show
    @booking = Booking.find(params[:restaurant_id])
  end

  def create
    @booking = Booking.new(bookings_params)
    @booking.user = current_user
    @booking.restaurant = Restaurant.find(params[:restaurant_id])
    @booking.status = "pending"
    if @booking.save
      redirect_to user_path(@booking.user)
    else
      render "restaurants/show"
    end
  end

  def accept
    @booking = Booking.find(params[:id])
    @booking.status = "accepted"
    if @booking.save
      redirect_to user_path(@booking.user) #page profil user @booking.restaurant.user pour proprio restaurant, sinon @booking.user = mangeur
    end
  end

  def reject
    @booking = Booking.find(params[:id])
    @booking.status = "declined"
    if @booking.save
      redirect_to user_path(@booking.user) #page profil user @booking.restaurant.user pour proprio restaurant, sinon @booking.user = mangeur
    end
  end

   def bookings_params
    params.require(:booking).permit(:status, :booking_date )
    # ajouter la date
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:home]

  def home
  end
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
 before_action :set_restaurant, only: [:show, :edit, :update, :destroy ]
 skip_before_action :authenticate_user!, only: [:search, :show]
  def new
    @restaurant = Restaurant.new
  end

  def index
    if params[:search] && params[:search] != ""
      @restaurants = Restaurant.near(params[:search],2)
    else
    @restaurants = Restaurant.where.not(latitude: nil, longitude: nil)
  end
    @hash = Gmaps4rails.build_markers(@restaurants) do |restaurant, marker|
      marker.lat restaurant.latitude
      marker.lng restaurant.longitude
      marker.json({id: restaurant.id})
      marker.picture({
        url: ActionController::Base.helpers.image_path('mark.png'),
        width:  50,
        height: 50
      })
      marker.infowindow render_to_string(partial: "pages/restaurant_map_box", locals: { restaurant: restaurant })
    end
  end

  def show
    @booking = Booking.new
    @hash = Gmaps4rails.build_markers(@restaurant) do |restaurant, marker|
      marker.lat restaurant.latitude
      marker.lng restaurant.longitude
      marker.infowindow render_to_string(partial: "pages/restaurant_map_box", locals: { restaurant: restaurant })
    end
  end

  def new
    @restaurant = Restaurant.new
  end

  def create
    @restaurant = Restaurant.new(restaurants_params)
    @restaurant.user = current_user
    if @restaurant.save
      redirect_to restaurant_path(@restaurant)
    else
      render :new
    end
  end

  # def search
  #   @search = params[:search]
  #   if params[:search] =! ""
  #     @users = User.near("#{params[:search]}", 5)
  #     @restaurants = find_restaurants_by_location(@users)
  #   else
  #     @restaurants = Restaurant.all
  #     @users = User.all
  # end

  # def find_restaurants_by_location(users)
  #   restaurants_array = []
  #   user_restaurants_array = []
  #   users.each do |user|
  #     user.restaurants.each do |restaurant|
  #       user_restaurants_array << restaurant
  #     end
  #   end
  #   user_restaurants_array.each do |restaurant|
  #     restaurants_array << restaurant
  #   end
  # return restaurants_array
  #   end
  # end

  private

  def set_restaurant
    @restaurant = Restaurant.find(params[:id])
  end

  def restaurants_params
    params.require(:restaurant).permit(:name, :description, :address, :zip, :city, :chef, :average_rating, :phone)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update]

  def show
  end

  def edit
  end

  def update
    @user.update(user_params)
    if @user.save
      redirect_to user_path(@user)
    else
      render :new
    end
  end

  private
  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:first_name, :last_name, :email)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/index.html.erb
<div class="container text-justify">
  <h1>My bookings</h1>

  <% @bookings.each do |booking| %>
    <strong><p><%= booking.status %></p></strong>
    <h4><%= booking.booking_date %></h4>
    <p><%= booking.restaurant.name %></p>
    <p><%= booking.user.email %></p>
    <%= link_to "Valider Reservation", accept_booking_path(booking) %>
    <%= link_to "Decliner Reservation", reject_booking_path(booking) %>
    <br><br>
  <% end %>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
     <meta charset="utf-8">
      <meta name="viewport" content="width=device-width, initial-scale=1">
      <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <link href="https://fonts.googleapis.com/css?family=Palanquin|Voltaire" rel="stylesheet">

    <title>Restaurants</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
  </head>
  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>
    <%= yield %>
   <%= javascript_include_tag "https://maps.google.com/maps/api/js?libraries=places&key=#{ENV['GOOGLE_API_BROWSER_KEY']}" %>
    <%= javascript_include_tag "https://cdn.rawgit.com/printercu/google-maps-utility-library-v3-read-only/master/markerclusterer/src/markerclusterer_compiled.js" %>
    <%= javascript_include_tag "https://cdn.rawgit.com/printercu/google-maps-utility-library-v3-read-only/master/infobox/src/infobox_packed.js" %>
    <%= javascript_include_tag 'application' %>
    <%= yield(:after_js) %>
  </body>
</html>

app/views/pages/_restaurant_map_box.html.erb
<div class="map_box">
  <h4><%= restaurant.name %></h4>
  <p><%= restaurant.address %></p>
  <p>Tel: <%= restaurant.phone %></p>
  <%= link_to 'Réserver', restaurant_path(restaurant), method: :post, class: "btn btn-map" %>
</div>

app/views/pages/home.html.erb
<%= content_for :flashes do %>
  <%= render "shared/flashes" %>
<% end %>
<div class="banner" style="background-image: linear-gradient(-225deg, rgba(211, 149, 155, -0.5), rgba(191, 230, 186, 0.5) 75%), url('<%= image_path("background.jpg") %>');">
  <div class="banner-content">
    <h1>La cuisine au beurre</h1>
    <div class="tagline">
      <p>"Il faut vivre pour manger et non pas manger pour vivre"</p>
      <p>N'en déplaise à Harpagon</p>

      <div></div>
      <div></div>
      <% if user_signed_in? %>

        <%= link_to "Le Beurre", restaurants_path, class: "btn btn-medium" %>
      <% else %>
        <%= link_to "S'INSCRIRE", new_user_registration_path, class: "btn btn-medium" %>
      <% end %>
    </div>

    <div class="learn-more">
      <span><a href="#about"><i class="fa fa-angle-down" id="arrow-down" aria-hidden="true"></i></a></span>
    </div>
  </div>
</div>
<div class="container-fluid intro" id="about">
    <h3>About La cuisine au beurre</h3>
    <p>Découvrir les meilleurs restaurants des plus modestes au plus dispendieux à travers le portrait des chefs et brigades</p>
    <p>...</p>
</div>

<div class="zone-circle">
  <div class="container text-center padded features">
    <div class="row">
      <div class="col-xs-12 col-sm-6 col-md-4">
        <%= image_tag "wine.svg", class: "small_image" %>
        <h4>Adjudant Chef</h4>
        <p>La cuisine c'est une histoire d'hommes et de femmes passionés</p>
      </div>
      <div class="col-xs-12 col-sm-6 col-md-4">
        <%= image_tag "gift.svg", class: "small_image" %>
        <h4>Généreux</h4>
        <p>Se manger les doigts, nous on aime pas</p>
      </div>
      <div class="col-xs-12 col-sm-6 col-md-4">
        <%= image_tag "heart.svg", class: "small_image" %>
        <h4>Mijotés avec Amour</h4>
        <p>La bonne cuisine, c'est le souvenir</p>
      </div>
    </div>
  </div>
</div>

<footer class="container-fluid footer">
  <div class="container">
    <a href="#" target="_blank"><i class="fa fa-facebook"></i></a>
    <a href="#" target="_blank"><i class="fa fa-twitter"></i></a>
    <a href="#" target="_blank"><i class="fa fa-linkedin"></i></a>
  </div>
</footer>

app/views/restaurants/_form.html.erb
<div class="banner" style="background-image: linear-gradient(-125deg, rgba(5,101,168,0.5) 0%, rgba(0,36,61,0.4) 20%), url('<%= image_path('background.jpg')%>');">
  <div class="container">
    <div class="form-row">
      <div class="col-sm-4 col-sm-offset-4">
        <div class="logins">
          <p class="logins-title">Ajouter un restaurant</p>
            <%= simple_form_for(@restaurant) do |f| %>
              <%= f.error_notification %>

              <div class="form-inputs input-claire">
                <%= f.input :name, placeholder: "Le nom du restaurant", label: false %>
                <%= f.input :chef, placeholder: "Ouh la toque", label: false %>
                <%= f.input :address, input_html: { class: "address-autocomplete" }, label: false %>
                <%= f.input :description, placeholder: "C'était comment?", label: false %>
                <%= f.input :phone, placeholder: "Tel", label: false %>
                <%= f.input :average_rating, placeholder: "0 - 5 ?", label: false %>
             <!--    <%= f.input attachinary %> -->
              </div>

              <div class="form-action">

              <%= f.submit "Mettre à jour", class: "form-button" %>
              <%= link_to "Retour", user_path(current_user), class: "back-button" %>
              </div>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>

app/views/restaurants/index.html.erb
  <div class="col-xs-3 col-sm-3">
  <div class="row desktop-wrap">
  </div>
    <div class="row position-fixed">
          <% @restaurants.each do |restaurant| %>
                  <h2><%= restaurant.name %></h2>
                    <p><%= restaurant.address %> <%= restaurant.city %> <%= restaurant.zip %></p>
                    <p>Tel: <%= restaurant.phone %></p>
                    <p><%= restaurant.average_rating%><i class="fa fa-star"></i></p>
                    <%= link_to "Détail", restaurant_path(restaurant), class: 'card-link' %>
      <% end %>
    </div>
  </div>
  <div class="col-xs-9 col-sm-9">
    <div class="row">
      <div id="map"></div>
    </div>
  </div>

<% content_for(:after_js) do %>
  <script>
  var styles = [
    {
        "featureType": "all",
        "elementType": "labels.text",
        "stylers": [
            {
                "color": "#000000"
            },
            {
                "visibility": "simplified"
            }
        ]
    },
    {
        "featureType": "all",
        "elementType": "labels.text.fill",
        "stylers": [
            {
                "hue": "#ff0000"
            }
        ]
    },
    {
        "featureType": "all",
        "elementType": "labels.text.stroke",
        "stylers": [
            {
                "color": "#ff0000"
            },
            {
                "visibility": "simplified"
            }
        ]
    },
    {
        "featureType": "administrative",
        "elementType": "labels.text.fill",
        "stylers": [
            {
                "color": "#000000"
            },
            {
                "visibility": "off"
            }
        ]
    },
    {
        "featureType": "administrative.country",
        "elementType": "geometry.fill",
        "stylers": [
            {
                "visibility": "off"
            },
            {
                "color": "#ff0000"
            }
        ]
    },
    {
        "featureType": "administrative.country",
        "elementType": "geometry.stroke",
        "stylers": [
            {
                "visibility": "on"
            }
        ]
    },
    {
        "featureType": "administrative.country",
        "elementType": "labels",
        "stylers": [
            {
                "visibility": "simplified"
            },
            {
                "color": "#9b30f2"
            }
        ]
    },
    {
        "featureType": "administrative.province",
        "elementType": "all",
        "stylers": [
            {
                "visibility": "off"
            }
        ]
    },
    {
        "featureType": "administrative.locality",
        "elementType": "all",
        "stylers": [
            {
                "visibility": "simplified"
            },
            {
                "color": "#7620bd"
            }
        ]
    },
    {
        "featureType": "landscape.man_made",
        "elementType": "all",
        "stylers": [
            {
                "visibility": "off"
            }
        ]
    },
    {
        "featureType": "landscape.man_made",
        "elementType": "geometry",
        "stylers": [
            {
                "visibility": "off"
            }
        ]
    },
    {
        "featureType": "landscape.man_made",
        "elementType": "geometry.fill",
        "stylers": [
            {
                "visibility": "off"
            }
        ]
    },
    {
        "featureType": "landscape.man_made",
        "elementType": "geometry.stroke",
        "stylers": [
            {
                "visibility": "off"
            }
        ]
    },
    {
        "featureType": "landscape.man_made",
        "elementType": "labels",
        "stylers": [
            {
                "visibility": "off"
            }
        ]
    },
    {
        "featureType": "landscape.natural",
        "elementType": "all",
        "stylers": [
            {
                "visibility": "off"
            }
        ]
    },
    {
        "featureType": "landscape.natural",
        "elementType": "geometry",
        "stylers": [
            {
                "visibility": "off"
            }
        ]
    },
    {
        "featureType": "landscape.natural",
        "elementType": "geometry.fill",
        "stylers": [
            {
                "visibility": "off"
            }
        ]
    },
    {
        "featureType": "landscape.natural.landcover",
        "elementType": "all",
        "stylers": [
            {
                "visibility": "on"
            }
        ]
    },
    {
        "featureType": "landscape.natural.terrain",
        "elementType": "all",
        "stylers": [
            {
                "visibility": "off"
            }
        ]
    },
    {
        "featureType": "poi",
        "elementType": "all",
        "stylers": [
            {
                "visibility": "off"
            }
        ]
    },
    {
        "featureType": "road",
        "elementType": "all",
        "stylers": [
            {
                "saturation": -100
            },
            {
                "lightness": 45
            },
            {
                "visibility": "simplified"
            }
        ]
    },
    {
        "featureType": "road.highway",
        "elementType": "all",
        "stylers": [
            {
                "visibility": "simplified"
            },
            {
                "color": "#c4c6f4"
            }
        ]
    },
    {
        "featureType": "road.highway",
        "elementType": "labels",
        "stylers": [
            {
                "visibility": "off"
            },
            {
                "color": "#d3d4f3"
            }
        ]
    },
    {
        "featureType": "road.highway",
        "elementType": "labels.text",
        "stylers": [
            {
                "visibility": "simplified"
            },
            {
                "color": "#000000"
            },
            {
                "weight": "0.01"
            }
        ]
    },
    {
        "featureType": "road.highway",
        "elementType": "labels.text.fill",
        "stylers": [
            {
                "visibility": "simplified"
            },
            {
                "weight": "0.01"
            }
        ]
    },
    {
        "featureType": "transit.station.bus",
        "elementType": "all",
        "stylers": [
            {
                "visibility": "off"
            }
        ]
    },
    {
        "featureType": "water",
        "elementType": "all",
        "stylers": [
            {
                "color": "#eeeeff"
            },
            {
                "visibility": "on"
            }
        ]
    }
]
    ;
    $(document).ready(function() {

      var handler = Gmaps.build('Google')
      handler.buildMap({ provider: {
          styles: styles
          // pass in other Google Maps API options here
          // => https://developers.google.com/maps/documentation/javascript/reference#MapOptions
          },
        internal: { id: 'map' } }, function() {
        markers = handler.addMarkers(<%= raw @hash.to_json %>);
        handler.bounds.extendWith(markers);
        handler.fitMapToBounds();
        if (markers.length == 0) {
          handler.getMap().setZoom(2);
        } else if (markers.length == 1) {
          handler.getMap().setZoom(14);
        }
      });
    });
  </script>
<% end %>

app/views/restaurants/new.html.erb
<%= render 'form' %>

app/views/restaurants/show.html.erb
<div class="padded">
  <div class="container media">
    <div class="row" class="media-body">
      <div class="col-xs-8 col-sm-8">
        <div class="restaurant-name">
            <h2><%= @restaurant.name %></h4>
            <h4><%= @restaurant.chef %></h4>
            <p><%= @restaurant.description %></p>
            <p><%= @restaurant.address %></p>
            <p><%= @restaurant.phone %></p>
            <p><%= @restaurant.average_rating %></p>
            <%= link_to "Back", restaurants_path %>
        </div>
      </div>
    </div>
    <div class="col-xs-4 col-sm-4">
        <div class="card-top">
          <h4 style ="color: white"><%= @restaurant.chef %></h4>
        </div>
        <div class="card-form">
          <div class="text-center " id="form-container">
            <%= simple_form_for [@restaurant, @booking] do |f| %>
            <%= f.error_notification %>
            <div class="form-inputs">
              <%= f.input :booking_date, as: :datetime %>
            </div>
            <div>
              <%= f.button :submit, class: "form-actions btn-book", value: "Réserver" %>
            </div>
            <% end %>
          </div>
        </div>
      <div class="col-xs-12 col-sm-12">
    <div class="row">
      <div id="map"></div>
    </div>
  </div>
</div>


<% content_for(:after_js) do %>
  <script>
  $(document).ready(function() {
    var handler = Gmaps.build('Google');
    handler.buildMap({ internal: { id: 'map' } }, function() {
      provider: {
        scrollwheel :false
      }
      markers = handler.addMarkers(<%= raw @hash.to_json %>);
      handler.bounds.extendWith(markers);
      handler.fitMapToBounds();
      if (markers.length == 0) {
        handler.getMap().setZoom(2);
      } else if (markers.length == 1) {
        handler.getMap().setZoom(14);
      }
    });
  })
</script>
<% end %>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon">
  <!-- Logo -->
  <%= link_to root_path, class: "navbar-wagon-brand" do %>
    <%= image_tag "logo.png" %>
  <% end %>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">

    <!-- Different navigation if login or not -->
    <% if user_signed_in? %>
    <!-- Text link Profile and Log-out -->

      <div id="navbar-links">
      <%= link_to "RestO", restaurants_path %>
      <%= link_to "Profil", user_path(current_user) %>
      <%= link_to "Déconnexion", destroy_user_session_path, method: :delete %>
      </div>
    <% else %>

      <!-- Login text link -->
      <div id= "navbar-links-login">
      <%= link_to t(".sign_in", default: "Se connecter"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %>
      </div>
    <% end %>
  </div>
</div>

app/views/users/edit.html.erb
<div class="banner" style="background-image: linear-gradient(-125deg, rgba(5,101,168,0.5) 0%, rgba(0,36,61,0.4) 20%), url('<%= image_path('background.jpg')%>');">
  <div class="container">
    <div class="form-row">
      <div class="col-sm-4 col-sm-offset-4">
        <div class="logins">
          <p class="logins-title">Update your profile</p>
            <%= simple_form_for(@user) do |f| %>
              <%= f.error_notification %>

              <div class="form-inputs input-claire">
                <%= f.input :first_name%>
                <%= f.input :last_name %>
                <%= f.input :email %>
              </div>

              <div class="form-action">

              <%= f.submit "Update", class: "form-button" %>
              <%= link_to "Back", user_path(current_user), class: "back-button" %>
              </div>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>

app/views/users/show.html.erb
<div class="container text-center">
  <div class="row">
    <div class="col-xs-12">
      <div id="profile-claire">

      <!-- if user photo -->
        <div id="profile-name" class="text-center">
          <%= @user.first_name %> <%= @user.last_name %>
        </div>

        <div id="metrics">
          <div id="metrics-restaurant">
            <%= image_tag "logo.png", {class: "img-circle", style: "height: 30px"} %>
            <p><%= @user.restaurants.count %> restaurants</p>
          </div>

          <div id="metrics-bookings">
            <%= image_tag "logo.png", {class: "img-circle", style: "height: 30px"}  %>
            <p><%= @user.bookings.count %> bookings</p>
          </div>
        </div>

        <div id="description">
          <p>
            " <%= @user.description %> "
          </p>
        </div>

        <div id="update-profile">
          <%= link_to "Modifier", edit_user_path(@user), class: "link-right" %>
        </div>
      </div>
    </div>
  </div>
</div>


<div class="container_eleo">

  <!--   partie bookings des restaurants -->
  <% if @user.bookings.empty? %>
    <div class="my_bookings text-center">
      <%= image_tag "logo.png", {class: "img-circle", style: "height: 100px"}%>
      <p>Vous n'avez fait aucune réservation</p>
    </div>
  <% else %>
    <div class="my_bookings text-center">
      <div class="title_booking text-left" style="color: #0060BF; margin-left: 130px; border-bottom-style: solid, border-bottom-color: #0060BF; ">
        <h3>Vos réservations</h3>
      </div>

      <div class="row">
        <% @user.bookings.each do |booking| %>
        <div class="col-xs-12 col-lg-10 col-lg-offset-1">
          <div class="container_restaurants">
            <div class="my_restaurant" style="background-image: url('<%= cl_image_path booking.restaurant.photo.path %>')">
              <h4><%= booking.restaurant.name %></h4>
               <h4><%= booking.restaurant.booking_date %></h4>
              <% if booking.status == "pending" %>
                <div class="badge badge-orange"><i class="fa fa-question" aria-hidden="true"></i></div>
              <% elsif booking.status == "accepted" %>
                <div class="badge badge-green"><i class="fa fa-check" aria-hidden="true"></i></div>
              <% elsif booking.status == "declined" %>
                <div class="badge badge-red"><i class="fa fa-times" aria-hidden="true"></i></div>
              <% end %>
            </div>

            <div class="restaurant_booking">
              <p>Vous fait une demande de reservation pour <strong><%= booking.restaurant.name %></strong> pour le  <%= booking.booking_date.to_formatted_s(:long) %></p>
            </div>
          </div>
        </div>
        <% end %>
      </div>
    </div>
  <% end %>

  <!-- partie des restaurants -->
  <% if @user.restaurant.empty? %>
    <div class="my_bookings text-center">
      <p>Vous n'avez aucune vache en location</p>
      <br>
      <%= link_to "Ajouter une vache", new_restaurant_path, class: "btn-add-restaurant" %>
    </div>
  <% else %>
  <div class="my_bookings text-center">
    <div class="title_booking text-left">
      <h3>Votre cohorte de vaches</h3>
      <%= link_to "Ajouter une vache", new_restaurant_path, class: "btn-add-restaurant" %>
    </div>
    <% @user.restaurants.each do |restaurant| %>
      <div class="row">
        <div class="col-xs-12 col-lg-10 col-lg-offset-1">
          <div class="container_restaurants">
            <div class="my_restaurant" style="background-image: url('<%= cl_image_path restaurant.photo.path %>')">
              <h4><%= restaurant.name %></h4>
            </div>
            <div class="restaurant_booking">
              <% if restaurant.bookings.empty? %>
                <p>Aucune réservation n'a été faite pour l'instant</p>
              <% else %>
                <ul>
                  <% restaurant.bookings.each do |booking| %>
                  <li><strong><%= booking.status.upcase %></strong> <%= booking.user.first_name %> a fait une réservation du <%= booking.start_date.to_formatted_s(:long) %> au <%= booking.end_date.to_formatted_s(:long) %>
                    <div class="btn-resa">
                      <%= link_to accept_booking_path(booking), class: "btn-accept" do %>
                        <i class="fa fa-check" aria-hidden="true"></i>
                      <% end %>
                      <%= link_to reject_booking_path(booking), class: "btn-decline" do %>
                        <i class="fa fa-times" aria-hidden="true"></i>
                      <% end %>
                    </div>
                  </li>
                  <% end %>
                </ul>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    <% end %>
    <br>
    <br>
    </div>
  <% end %>

</div>